#POST http://localhost:4020/api/transaction/outcome
#Content-Type: application/json Cookie: key=first-value
#{
#    "company":
#     {
#        "id": 1,
#        "name": "Apple",
#        "balance": 800
#    },
#    "transactionValue": 200
#}
GET http://localhost:4020/api/hello_world
#//
#		<dependency>
#			<groupId>org.springframework.boot</groupId>
#			<artifactId>spring-boot-starter-security</artifactId>
#		</dependency>
#<dependency>
#			<groupId>org.springframework.security</groupId>
#			<artifactId>spring-security-test</artifactId>
#			<scope>test</scope>
#		</dependency>